server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/planner_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
